//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinDinkedit.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SPRITE_LIBRARY              102
#define IDD_SPRITE_PROPERTIES           107
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_WINDINTYPE                  129
#define IDD_SCREEN_PROPERTIES           129
#define IDR_SPRITE_MENU                 130
#define IDR_SCREEN_MENU                 131
#define IDD_VISION                      133
#define IDR_NEW_SCREEN                  134
#define IDR_SIDEBAR                     136
#define IDD_IMPORT_SCREEN               137
#define IDR_SPRITE_ENTRY                138
#define IDD_FFCREATE                    139
#define IDR_SCREEN_MENU1                139
#define IDR_HARD_MENU                   139
#define IDD_COMPRESS_SCRIPTS            140
#define IDD_OPEN_DMOD                   141
#define IDD_OPTIONS                     145
#define IDD_NEW_DMOD                    150
#define IDD_DMOD_PROPERTIES             152
#define IDD_UPDATE                      153
#define ID_FILE_PLAYGAME                156
#define ID_SAVE_FIX                     157
#define ID_SCREENPROPERTIES_SCREEN      157
#define ID_SCREENPROPERTIES_HARD        158
#define IDM_EDIT_HARDNESS               159
#define IDM_SET_DEFAULT_HARD_TILE       160
#define ID_SCREENPROPERTIES_SCREEN163   163
#define IDD_GETFOLDER_DIALOG            164
#define ID_SCREENPROPERTIES_SPRITE      164
#define IDC_Script                      1002
#define IDC_Strength                    1006
#define IDC_Defense                     1007
#define IDC_Hitpoints                   1008
#define IDC_Speed                       1009
#define IDC_Vision                      1010
#define IDC_Base_idle                   1011
#define IDC_Base_walk                   1012
#define IDC_Base_attack                 1013
#define IDC_Sound                       1014
#define IDC_Touch_sequence              1015
#define IDC_Touch_damage                1016
#define IDC_Warp_screen                 1017
#define IDC_Warp_x                      1018
#define IDC_Warp_y                      1019
#define IDC_Sequence                    1020
#define IDC_Frame                       1021
#define IDC_Y                           1022
#define IDC_X                           1023
#define IDC_Timing                      1025
#define IDC_Base_death                  1026
#define IDC_Nohit                       1028
#define IDC_Hard                        1029
#define IDC_Enable_warp                 1030
#define IDC_Depth_que                   1031
#define IDC_Inside                      1032
#define IDC_Midi                        1035
#define IDC_Size                        1039
#define IDC_BRAIN                       1040
#define IDC_ORNAMENTAL                  1041
#define IDC_RADIO2                      1042
#define IDC_INVISIBLE                   1043
#define IDC_Experience_Given            1044
#define IDC_EDIT_SPRITE_SCRIPT          1048
#define IDC_DMOD_IMPORT_LIST            1049
#define IDC_Name                        1050
#define IDC_DELETE_GRAPHICS             1051
#define IDC_DELETE_C_FILES              1052
#define IDC_REMOVE_COMMENTS             1053
#define IDC_SCREEN_GAP                  1055
#define IDC_DMOD_LIST                   1056
#define IDC_DMOD_DIRECTORY_NAME         1059
#define IDC_DMOD_TITLE                  1060
#define IDC_DMOD_DESCRIPTION            1064
#define IDC_EMAIL_WEBSITE               1065
#define IDC_AUTHOR                      1066
#define IDC_MAX_UNDOS                   1067
#define IDC_AUTO_SAVE                   1068
#define IDC_SHOW_PROGRESS               1069
#define IDC_PROGRESS                    1070
#define IDC_BRUSH_SIZE                  1070
#define IDC_UPDATE                      1071
#define IDC_DINK_INI                    1073
#define IDC_OPTIMIZED_MINI_MAP          1074
#define IDC_FAST_MINIMAP                1074
#define IDC_CHECK1                      1075
#define IDC_HOVER_SPRITE_INFO           1075
#define IDC_CHECK2                      1076
#define IDC_HELP_TEXT                   1077
#define IDC_COMBO1                      1078
#define IDC_HELP_TEXT_COLOR             1078
#define IDC_ED_FOLDER                   1079
#define ID_GETFOLDER                    1080
#define IDM_PROPERTIES                  32774
#define IDM_SPRITE_PROPERTIES           32775
#define ID_SCREEN_PROPERTIES            32776
#define ID_DELETE_SCREEN                32777
#define IDM_VISION                      32778
#define IDM_NEW_SCREEN                  32779
#define IDM_VIEW_MINIMAP                32780
#define IDM_VIEW_SPRITE_MODE            32782
#define IDM_VIEW_TILE_MODE              32783
#define IDM_VIEW_SPRITE_SELECTOR        32785
#define IDM_SCREEN_MATCH                32786
#define IDM_VIEW_TILESET_1              32787
#define IDM_VIEW_TILESET_3              32788
#define IDM_VIEW_TILESET_4              32789
#define IDM_VIEW_TILESET_5              32790
#define IDM_VIEW_TILESET_6              32791
#define IDM_VIEW_TILESET_7              32792
#define IDM_VIEW_TILESET_8              32793
#define IDM_VIEW_TILESET_9              32794
#define IDM_VIEW_TILESET_10             32795
#define IDM_VIEW_TILESET_11             32796
#define IDM_VIEW_TILESET_2              32797
#define IDM_SPRITE_HARDNESS             32798
#define IDM_VIEW_HARDBOX_MODE           32799
#define IDM_SET_WARP_END                32800
#define IDM_SET_WARP_BEGIN              32801
#define IDM_VIEW_HARD_TILE_SELECTOR     32802
#define IDM_REFRESH_LIST                32803
#define IDM_IMPORT_SCREEN               32804
#define IDM_AUTO_UPDATE_MINIMAP         32805
#define IDM_SCREEN_SHOT                 32806
#define IDM_STORE_SPRITE                32807
#define IDM_DELETE_SPRITE_ENTRY         32809
#define IDM_COPY_SCREEN                 32811
#define IDM_PASTE_SCREEN                32812
#define IDM_COMPRESS_SCRIPTS            32813
#define IDM_OPTIONS                     32814
#define IDM_FFCREATE                    32815
#define IDM_RENAME_SPRITE_ENTRY         32816
#define ID_NEW_DMOD                     32818
#define ID_DMOD_PROPERTIES              32819
#define ID_INDICATOR_MOUSE              59142
#define ID_INDICATOR_VISION             59143
#define ID_INDICATOR_SCR_MATCH          59144
#define ID_INDICATOR_SPR_HARD           59145
#define IDM_REVERT_HARD_TILE            59161
#define IDM_TRANSFORM_HARDNESS_NORMAL   59171
#define IDM_TRANSFORM_HARDNESS_LOW      59172
#define IDM_TRANSFORM_HARDNESS_UNKNOWN  59173

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
